#!/usr/bin/env node
/* Generates icons.js from the SVG files in icons/.

   The SVGs are exported from the "iOS icons" frame (2428:5548) and the tab-bar
   icon components on the "Icons WIP" page of the Playlist Design System Figma
   file, then normalised so every painted colour is `currentColor` — an icon
   takes the colour of whatever it sits in. A couple icons are two-tone by
   design and paint fixed colours instead of `currentColor`.

   Exact-export exceptions — do not redraw, re-trace, or hand-edit path data;
   if the source artwork changes, replace the file wholesale with the new export:
   - star-fill / star-half / star-outline: iOS star SVGs (`#FFB54D` / `#B3B5BC`)
   - chevron-down-small / chevron-up-small: exact copies of
     `assets/iOS_chevron_down_small.svg` / `assets/iOS_chevron_up_small.svg`
   - calendar-add: exact copy of `assets/iOS_calendar_add.svg` (24×24, `currentColor`
     in icons/ for the sprite; baked `#020203` kept in assets/)
   - calendar-add-16: exact copy of `assets/calendar_add_16.svg` (20×18, `currentColor`
     in icons/ for the sprite; baked `#020203` kept in assets/). 16pt SF Symbol
     weight for Small button slots — not a scaled-down `#pl-calendar-add`.
   - calendar-empty: exact copy of `assets/calendar_empty state.svg` (45×44,
     `currentColor` in icons/ for the sprite; baked `#020203` kept in
     `assets/calendar_empty_state.svg`)
   - share-small: exact copy of `assets/iOS_share_small.svg` (24×24, `currentColor`
     in icons/ for the sprite; baked `#020203` kept in assets/)
   - ios-info: exact copy of `assets/iOS_info.svg` (20×20, `currentColor`
     in icons/ for the sprite; baked `#020203` kept in assets/)
   - map-pin: exact copy of `assets/Map card pin.svg` (49×52, baked red/white
     plus its drop-shadow filter). IDs are kept so the filter url(#…) still
     resolves. A map marker shouldn't invert in dark mode.

   icons.js injects an inline <symbol> sprite rather than shipping the files as
   external references, because `<use href="file.svg#id">` is blocked on
   file:// and these prototypes get opened directly as often as they get served.

   Run after adding or re-exporting an icon:  node design-system/build-icons.mjs
*/

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = new URL('./icons/', import.meta.url).pathname;

/* Display order on the design-system page. Anything not listed still ships —
   it lands in "Other" so a newly-exported icon is never silently dropped. */
const GROUPS = [
  ['Navigation', ['back', 'close', 'chevron-down', 'chevron-down-small', 'chevron-up-small', 'right-chevron', 'search', 'share', 'share-small']],
  ['Contact & place', ['location-pin', 'location-pin-small', 'person-small',
                       'directions', 'phone', 'globe', 'tag', 'map-pin']],
  ['Booking', ['calendar-small', 'calendar-add', 'calendar-add-16', 'calendar-large', 'calendar-empty', 'stack']],
  ['Rating', ['star-fill', 'star-half', 'star-outline']],
  ['Auth & form', ['apple-logo', 'eye', 'eye-slash', 'small-info', 'ios-info']],
  ['Tab bar', ['tab-home', 'tab-search', 'tab-bookings', 'tab-profile']],
];

const files = readdirSync(DIR).filter((f) => f.endsWith('.svg'));
const names = new Set(files.map((f) => f.replace(/\.svg$/, '')));

const groups = GROUPS.map(([name, list]) => {
  const present = list.filter((n) => names.has(n));
  present.forEach((n) => names.delete(n));
  return { name, names: present };
}).filter((g) => g.names.length);

if (names.size) groups.push({ name: 'Other', names: [...names].sort() });

const missing = GROUPS.flatMap(([, l]) => l).filter((n) => !readdirSync(DIR).includes(n + '.svg'));
if (missing.length) console.warn(`WARNING: grouped but not on disk: ${missing.join(', ')}`);

/* Each file becomes a <symbol>. The viewBox carries over verbatim: SF Symbol
   outlines routinely overflow the 16/20/24 frame they sit in, so the artwork's
   own bounds are what make it centre correctly inside a square slot. */
const symbols = groups.flatMap((g) => g.names).map((name) => {
  const raw = readFileSync(join(DIR, `${name}.svg`), 'utf8');
  const viewBox = (raw.match(/viewBox="([^"]+)"/) || [])[1];
  if (!viewBox) throw new Error(`${name}.svg has no viewBox`);
  /* map-pin's drop shadow is `filter="url(#filter0_d_…)"` — stripping ids
     would break the reference. Other icons have no internal id refs. */
  const stripped = name === 'map-pin' ? raw : raw.replace(/ id="[^"]*"/g, '');
  const body = stripped
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim();
  return `<symbol id="pl-${name}" viewBox="${viewBox}">${body}</symbol>`;
});

const out = `/* Generated by build-icons.mjs — do not edit by hand.
   Source: "iOS icons" frame + tab-bar icons on the "Icons WIP" page of the
   Playlist Design System Figma file (VMrMBZC3y8lOfxic25V7HT).

   Injects an inline SVG sprite on load, then:
     <svg class="pl-icon" aria-hidden="true"><use href="#pl-back"></use></svg>

   window.PL_ICONS is the grouped name list, for the design-system page. */
window.PL_ICONS = ${JSON.stringify(groups, null, 2)};

(function () {
  var SPRITE = '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"' +
    ' style="position:absolute;width:0;height:0;overflow:hidden">' +
    ${JSON.stringify(symbols.join(''))} +
    '</svg>';

  function inject() {
    if (document.getElementById('pl-icon-sprite')) return;
    var host = document.createElement('div');
    host.id = 'pl-icon-sprite';
    host.setAttribute('aria-hidden', 'true');
    host.style.cssText = 'position:absolute;width:0;height:0;overflow:hidden';
    host.innerHTML = SPRITE;
    document.body.insertBefore(host, document.body.firstChild);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inject);
  } else {
    inject();
  }
})();

/* Convenience for prototypes that build markup as strings. */
window.plIconSvg = function (name, cls) {
  return '<svg class="pl-icon' + (cls ? ' ' + cls : '') + '" aria-hidden="true">' +
    '<use href="#pl-' + name + '"></use></svg>';
};

/* star-xs (2428:5472) — 16×16 slot with Figma's nested inset wrapper. */
window.plStarXsSvg = function (name) {
  return '<span class="pl-star-xs"><svg class="pl-icon" aria-hidden="true">' +
    '<use href="#pl-' + name + '"></use></svg></span>';
};
`;

writeFileSync(new URL('./icons.js', import.meta.url), out);
console.log(`Wrote icons.js — ${symbols.length} icons in ${groups.length} groups`);
groups.forEach((g) => console.log(`  ${g.name}: ${g.names.join(', ')}`));
