// Generated by postprocess-tokens.mjs — do not edit by hand.
window.PL_TOKENS = [
  {
    "name": "--pl-green-100",
    "value": "#EDFAF3"
  },
  {
    "name": "--pl-green-200",
    "value": "#D4F3E3"
  },
  {
    "name": "--pl-green-300",
    "value": "#B2E9CD"
  },
  {
    "name": "--pl-green-400",
    "value": "#8FDEB5"
  },
  {
    "name": "--pl-green-500",
    "value": "#6DD49F"
  },
  {
    "name": "--pl-green-600",
    "value": "#4DCB8A"
  },
  {
    "name": "--pl-green-700",
    "value": "#41AD75"
  },
  {
    "name": "--pl-red-100",
    "value": "#FEF5F5"
  },
  {
    "name": "--pl-red-200",
    "value": "#FDE2E2"
  },
  {
    "name": "--pl-red-300",
    "value": "#FBC1C1"
  },
  {
    "name": "--pl-red-400",
    "value": "#FAB2B2"
  },
  {
    "name": "--pl-red-500",
    "value": "#F23535"
  },
  {
    "name": "--pl-red-600",
    "value": "#E10E0E"
  },
  {
    "name": "--pl-red-700",
    "value": "#CA0D0D"
  },
  {
    "name": "--pl-purple-100",
    "value": "#F2EBFF"
  },
  {
    "name": "--pl-purple-200",
    "value": "#DFCCFF"
  },
  {
    "name": "--pl-purple-300",
    "value": "#C5A4FE"
  },
  {
    "name": "--pl-purple-400",
    "value": "#8F4EFD"
  },
  {
    "name": "--pl-purple-500",
    "value": "#7F35FD"
  },
  {
    "name": "--pl-purple-600",
    "value": "#6207FD"
  },
  {
    "name": "--pl-purple-700",
    "value": "#4E02CF"
  },
  {
    "name": "--pl-blue-100",
    "value": "#E9F3FF"
  },
  {
    "name": "--pl-blue-200",
    "value": "#CAE1FF"
  },
  {
    "name": "--pl-blue-300",
    "value": "#A1CAFF"
  },
  {
    "name": "--pl-blue-400",
    "value": "#75B1FF"
  },
  {
    "name": "--pl-blue-500",
    "value": "#4B99FF"
  },
  {
    "name": "--pl-blue-600",
    "value": "#2483FF"
  },
  {
    "name": "--pl-blue-700",
    "value": "#005DD6"
  },
  {
    "name": "--pl-yellow-100",
    "value": "#FFFCE6"
  },
  {
    "name": "--pl-yellow-200",
    "value": "#FFF9D4"
  },
  {
    "name": "--pl-yellow-300",
    "value": "#FFF5B2"
  },
  {
    "name": "--pl-yellow-400",
    "value": "#FFF08F"
  },
  {
    "name": "--pl-yellow-500",
    "value": "#FFEB6D"
  },
  {
    "name": "--pl-yellow-600",
    "value": "#FFE74D"
  },
  {
    "name": "--pl-yellow-700",
    "value": "#F0CF00"
  },
  {
    "name": "--pl-orange-100",
    "value": "#FFF4E6"
  },
  {
    "name": "--pl-orange-200",
    "value": "#FFEED6"
  },
  {
    "name": "--pl-orange-300",
    "value": "#FFDFB2"
  },
  {
    "name": "--pl-orange-400",
    "value": "#FFD08F"
  },
  {
    "name": "--pl-orange-500",
    "value": "#FFC16B"
  },
  {
    "name": "--pl-orange-600",
    "value": "#FFB54D"
  },
  {
    "name": "--pl-orange-700",
    "value": "#FFA01A"
  },
  {
    "name": "--pl-neutral-100",
    "value": "#F7F7F8"
  },
  {
    "name": "--pl-neutral-200",
    "value": "#F1F2F3"
  },
  {
    "name": "--pl-neutral-300",
    "value": "#E4E5E7"
  },
  {
    "name": "--pl-neutral-400",
    "value": "#D9DADD"
  },
  {
    "name": "--pl-neutral-500",
    "value": "#B3B5BC"
  },
  {
    "name": "--pl-neutral-600",
    "value": "#90939D"
  },
  {
    "name": "--pl-neutral-700",
    "value": "#35363B"
  },
  {
    "name": "--pl-neutral-50",
    "value": "#FFFFFF"
  },
  {
    "name": "--pl-neutral-900",
    "value": "#020203"
  },
  {
    "name": "--pl-green-800",
    "value": "#379062"
  },
  {
    "name": "--pl-green-900",
    "value": "#19432D"
  },
  {
    "name": "--pl-red-800",
    "value": "#A80A0A"
  },
  {
    "name": "--pl-red-900",
    "value": "#3A0303"
  },
  {
    "name": "--pl-purple-800",
    "value": "#4601BC"
  },
  {
    "name": "--pl-purple-900",
    "value": "#2D0178"
  },
  {
    "name": "--pl-blue-800",
    "value": "#0032D7"
  },
  {
    "name": "--pl-blue-900",
    "value": "#00285C"
  },
  {
    "name": "--pl-yellow-800",
    "value": "#BDA300"
  },
  {
    "name": "--pl-yellow-900",
    "value": "#473E00"
  },
  {
    "name": "--pl-orange-800",
    "value": "#E58600"
  },
  {
    "name": "--pl-orange-900",
    "value": "#6B3F00"
  },
  {
    "name": "--pl-neutral-800",
    "value": "#1D1D20"
  },
  {
    "name": "--pl-neutral-850",
    "value": "#161618"
  },
  {
    "name": "--pl-green-850",
    "value": "#296B49"
  },
  {
    "name": "--pl-red-850",
    "value": "#7D0707"
  },
  {
    "name": "--pl-orange-850",
    "value": "#A15F00"
  },
  {
    "name": "--pl-purple-850",
    "value": "#3C01A2"
  },
  {
    "name": "--pl-yellow-850",
    "value": "#5C4F00"
  },
  {
    "name": "--pl-blue-850",
    "value": "#002E6B"
  },
  {
    "name": "--pl-neutral-650",
    "value": "#43454C"
  },
  {
    "name": "--pl-neutral-750",
    "value": "#1F2023"
  },
  {
    "name": "--pl-space-0",
    "value": "0px"
  },
  {
    "name": "--pl-space-1",
    "value": "4px"
  },
  {
    "name": "--pl-space-2",
    "value": "8px"
  },
  {
    "name": "--pl-space-3",
    "value": "12px"
  },
  {
    "name": "--pl-space-4",
    "value": "16px"
  },
  {
    "name": "--pl-space-5",
    "value": "20px"
  },
  {
    "name": "--pl-space-6",
    "value": "24px"
  },
  {
    "name": "--pl-space-7",
    "value": "32px"
  },
  {
    "name": "--pl-space-8",
    "value": "40px"
  },
  {
    "name": "--pl-space-9",
    "value": "48px"
  },
  {
    "name": "--pl-space-10",
    "value": "64px"
  },
  {
    "name": "--pl-space-11",
    "value": "80px"
  },
  {
    "name": "--pl-space-12",
    "value": "96px"
  },
  {
    "name": "--pl-text-primary",
    "value": "var(--pl-neutral-900)"
  },
  {
    "name": "--pl-text-secondary",
    "value": "var(--pl-neutral-650)"
  },
  {
    "name": "--pl-text-disabled",
    "value": "var(--pl-neutral-500)"
  },
  {
    "name": "--pl-text-inverse",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-text-link",
    "value": "var(--pl-blue-800)"
  },
  {
    "name": "--pl-text-status-success",
    "value": "var(--pl-green-850)"
  },
  {
    "name": "--pl-text-status-warning",
    "value": "var(--pl-orange-850)"
  },
  {
    "name": "--pl-text-status-danger",
    "value": "var(--pl-red-700)"
  },
  {
    "name": "--pl-text-status-neutral",
    "value": "var(--pl-neutral-900)"
  },
  {
    "name": "--pl-text-status-red",
    "value": "var(--pl-red-800)"
  },
  {
    "name": "--pl-text-status-purple",
    "value": "var(--pl-purple-850)"
  },
  {
    "name": "--pl-text-status-green",
    "value": "var(--pl-green-850)"
  },
  {
    "name": "--pl-text-status-yellow",
    "value": "var(--pl-yellow-850)"
  },
  {
    "name": "--pl-text-status-orange",
    "value": "var(--pl-orange-850)"
  },
  {
    "name": "--pl-text-status-blue",
    "value": "var(--pl-blue-850)"
  },
  {
    "name": "--pl-bg-default",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-bg-subtle",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-bg-inverse",
    "value": "var(--pl-neutral-850)"
  },
  {
    "name": "--pl-surface-default",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-surface-inset",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-surface-static-black",
    "value": "var(--pl-neutral-850)"
  },
  {
    "name": "--pl-surface-disabled",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-surface-status-successsubtle",
    "value": "var(--pl-green-100)"
  },
  {
    "name": "--pl-surface-status-warningsubtle",
    "value": "var(--pl-orange-100)"
  },
  {
    "name": "--pl-surface-status-dangersubtle",
    "value": "var(--pl-red-100)"
  },
  {
    "name": "--pl-surface-variant-neutral",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-surface-variant-red",
    "value": "var(--pl-red-100)"
  },
  {
    "name": "--pl-surface-variant-purple",
    "value": "var(--pl-purple-100)"
  },
  {
    "name": "--pl-surface-variant-green",
    "value": "var(--pl-green-100)"
  },
  {
    "name": "--pl-surface-variant-yellow",
    "value": "var(--pl-yellow-100)"
  },
  {
    "name": "--pl-surface-variant-orange",
    "value": "var(--pl-orange-100)"
  },
  {
    "name": "--pl-surface-variant-blue",
    "value": "var(--pl-blue-100)"
  },
  {
    "name": "--pl-border-default",
    "value": "var(--pl-neutral-300)"
  },
  {
    "name": "--pl-border-disabled",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-border-danger",
    "value": "var(--pl-red-600)"
  },
  {
    "name": "--pl-accent-default",
    "value": "var(--pl-red-600)"
  },
  {
    "name": "--pl-accent-hover",
    "value": "var(--pl-red-500)"
  },
  {
    "name": "--pl-accent-pressed",
    "value": "var(--pl-red-700)"
  },
  {
    "name": "--pl-border-focus",
    "value": "var(--pl-neutral-850)"
  },
  {
    "name": "--pl-surface-subtle",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-surface-hover",
    "value": "var(--pl-neutral-300)"
  },
  {
    "name": "--pl-surface-pressed",
    "value": "var(--pl-neutral-400)"
  },
  {
    "name": "--pl-surface-selected",
    "value": "var(--pl-neutral-500)"
  },
  {
    "name": "--pl-text-emphasis",
    "value": "var(--pl-accent-default)"
  },
  {
    "name": "--pl-accent-subtle",
    "value": "var(--pl-red-200)"
  },
  {
    "name": "--pl-accent-subtlehover",
    "value": "var(--pl-red-300)"
  },
  {
    "name": "--pl-accent-subtlepressed",
    "value": "var(--pl-red-400)"
  },
  {
    "name": "--pl-accent-focusring",
    "value": "var(--pl-red-700)"
  },
  {
    "name": "--pl-border-subtle",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-icon-default",
    "value": "var(--pl-neutral-900)"
  },
  {
    "name": "--pl-icon-subtle",
    "value": "var(--pl-neutral-600)"
  },
  {
    "name": "--pl-icon-disabled",
    "value": "var(--pl-neutral-500)"
  },
  {
    "name": "--pl-icon-inverse",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-icon-green",
    "value": "var(--pl-green-600)"
  },
  {
    "name": "--pl-icon-red",
    "value": "var(--pl-red-600)"
  },
  {
    "name": "--pl-icon-orange",
    "value": "var(--pl-orange-600)"
  },
  {
    "name": "--pl-icon-yellow",
    "value": "var(--pl-yellow-600)"
  },
  {
    "name": "--pl-icon-purple",
    "value": "var(--pl-purple-600)"
  },
  {
    "name": "--pl-icon-blue",
    "value": "var(--pl-blue-600)"
  },
  {
    "name": "--pl-icon-rating",
    "value": "var(--pl-orange-600)"
  },
  {
    "name": "--pl-text-onaccent",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-text-price-discount",
    "value": "var(--pl-green-800)"
  },
  {
    "name": "--pl-icon-success",
    "value": "var(--pl-green-800)"
  },
  {
    "name": "--pl-surface-static-white",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-button-secondary-bg-default",
    "value": "var(--pl-accent-subtle)"
  },
  {
    "name": "--pl-button-secondary-bg-hovered",
    "value": "var(--pl-accent-subtlehover)"
  },
  {
    "name": "--pl-button-secondary-bg-pressed",
    "value": "var(--pl-accent-subtlepressed)"
  },
  {
    "name": "--pl-button-secondary-bg-disabled",
    "value": "var(--pl-red-100)"
  },
  {
    "name": "--pl-button-neutral-bg-default",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-button-neutral-bg-hovered",
    "value": "var(--pl-neutral-300)"
  },
  {
    "name": "--pl-button-neutral-bg-pressed",
    "value": "var(--pl-neutral-400)"
  },
  {
    "name": "--pl-button-neutral-bg-disabled",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-button-neutralsolid-bg-default",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-button-neutralsolid-bg-hovered",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-button-neutralsolid-bg-pressed",
    "value": "var(--pl-neutral-300)"
  },
  {
    "name": "--pl-button-neutralsolid-bg-disabled",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-button-outline-bg-default",
    "value": "#00000000"
  },
  {
    "name": "--pl-button-outline-bg-hovered",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-button-outline-bg-pressed",
    "value": "var(--pl-neutral-300)"
  },
  {
    "name": "--pl-button-outline-bg-disabled",
    "value": "#00000000"
  },
  {
    "name": "--pl-button-destructive-bg-default",
    "value": "var(--pl-red-500)"
  },
  {
    "name": "--pl-button-destructive-bg-hovered",
    "value": "var(--pl-red-600)"
  },
  {
    "name": "--pl-button-destructive-bg-pressed",
    "value": "var(--pl-red-700)"
  },
  {
    "name": "--pl-button-destructive-bg-disabled",
    "value": "var(--pl-red-200)"
  },
  {
    "name": "--pl-button-destructive-fg-disabled",
    "value": "var(--pl-text-onaccent)"
  },
  {
    "name": "--pl-button-destructive-fg-default",
    "value": "var(--pl-text-onaccent)"
  },
  {
    "name": "--pl-button-secondary-fg-default",
    "value": "var(--pl-accent-pressed)"
  },
  {
    "name": "--pl-button-secondary-fg-disabled",
    "value": "var(--pl-red-300)"
  },
  {
    "name": "--pl-button-neutral-fg-default",
    "value": "var(--pl-text-primary)"
  },
  {
    "name": "--pl-button-neutral-fg-disabled",
    "value": "var(--pl-text-disabled)"
  },
  {
    "name": "--pl-button-neutralsolid-fg-default",
    "value": "var(--pl-text-primary)"
  },
  {
    "name": "--pl-button-neutralsolid-fg-disabled",
    "value": "var(--pl-text-disabled)"
  },
  {
    "name": "--pl-button-outline-fg-default",
    "value": "var(--pl-text-primary)"
  },
  {
    "name": "--pl-button-outline-fg-disabled",
    "value": "var(--pl-text-disabled)"
  },
  {
    "name": "--pl-button-inverse-bg-default",
    "value": "var(--pl-neutral-900)"
  },
  {
    "name": "--pl-button-inverse-bg-hovered",
    "value": "var(--pl-neutral-700)"
  },
  {
    "name": "--pl-button-inverse-bg-pressed",
    "value": "var(--pl-neutral-850)"
  },
  {
    "name": "--pl-button-inverse-bg-disabled",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-button-inverse-fg-default",
    "value": "var(--pl-text-onaccent)"
  },
  {
    "name": "--pl-button-inverse-fg-disabled",
    "value": "var(--pl-text-disabled)"
  },
  {
    "name": "--pl-button-ghost-bg-default",
    "value": "#00000000"
  },
  {
    "name": "--pl-button-ghost-bg-hovered",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-button-ghost-bg-pressed",
    "value": "var(--pl-neutral-200)"
  },
  {
    "name": "--pl-button-ghost-bg-disabled",
    "value": "var(--pl-neutral-100)"
  },
  {
    "name": "--pl-button-ghost-fg-default",
    "value": "var(--pl-text-primary)"
  },
  {
    "name": "--pl-button-ghost-fg-disabled",
    "value": "var(--pl-text-disabled)"
  },
  {
    "name": "--pl-shadow-default",
    "value": "var(--pl-neutral-900)"
  },
  {
    "name": "--pl-text-static-black",
    "value": "var(--pl-neutral-900)"
  },
  {
    "name": "--pl-border-white",
    "value": "var(--pl-neutral-50)"
  },
  {
    "name": "--pl-type-weight-regular",
    "value": "400"
  },
  {
    "name": "--pl-type-weight-medium",
    "value": "500"
  },
  {
    "name": "--pl-type-weight-semibold",
    "value": "600"
  },
  {
    "name": "--pl-type-weight-bold",
    "value": "700"
  },
  {
    "name": "--pl-type-lineheight-100",
    "value": "16px"
  },
  {
    "name": "--pl-type-lineheight-200",
    "value": "20px"
  },
  {
    "name": "--pl-type-lineheight-300",
    "value": "24px"
  },
  {
    "name": "--pl-type-size-100",
    "value": "11px"
  },
  {
    "name": "--pl-type-size-200",
    "value": "12px"
  },
  {
    "name": "--pl-type-size-300",
    "value": "14px"
  },
  {
    "name": "--pl-type-size-400",
    "value": "16px"
  },
  {
    "name": "--pl-type-size-500",
    "value": "18px"
  },
  {
    "name": "--pl-type-size-600",
    "value": "20px"
  },
  {
    "name": "--pl-type-size-700",
    "value": "24px"
  },
  {
    "name": "--pl-type-size-800",
    "value": "28px"
  },
  {
    "name": "--pl-type-size-900",
    "value": "32px"
  },
  {
    "name": "--pl-type-size-1000",
    "value": "40px"
  },
  {
    "name": "--pl-type-size-1100",
    "value": "48px"
  },
  {
    "name": "--pl-type-lineheight-400",
    "value": "28px"
  },
  {
    "name": "--pl-type-lineheight-500",
    "value": "32px"
  },
  {
    "name": "--pl-type-lineheight-600",
    "value": "36px"
  },
  {
    "name": "--pl-type-lineheight-700",
    "value": "40px"
  },
  {
    "name": "--pl-type-lineheight-800",
    "value": "48px"
  },
  {
    "name": "--pl-type-lineheight-900",
    "value": "56px"
  },
  {
    "name": "--pl-type-weight-extrabold",
    "value": "800"
  },
  {
    "name": "--pl-type-font-primary",
    "value": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif"
  },
  {
    "name": "--pl-type-font-brand",
    "value": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif"
  },
  {
    "name": "--pl-type-weight-black",
    "value": "900"
  },
  {
    "name": "--pl-type-size-250",
    "value": "13px"
  },
  {
    "name": "--pl-type-lineheight-150",
    "value": "18px"
  },
  {
    "name": "--pl-type-lineheight-350",
    "value": "26px"
  },
  {
    "name": "--pl-type-lineheight-50",
    "value": "14px"
  },
  {
    "name": "--pl-display-xl-font",
    "value": "var(--pl-type-font-brand)"
  },
  {
    "name": "--pl-display-xl-size",
    "value": "var(--pl-type-size-1100)"
  },
  {
    "name": "--pl-display-xl-lineheight",
    "value": "var(--pl-type-lineheight-900)"
  },
  {
    "name": "--pl-display-xl-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-display-lg-font",
    "value": "var(--pl-type-font-brand)"
  },
  {
    "name": "--pl-display-lg-size",
    "value": "var(--pl-type-size-1000)"
  },
  {
    "name": "--pl-display-lg-lineheight",
    "value": "var(--pl-type-lineheight-800)"
  },
  {
    "name": "--pl-display-lg-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-display-md-font",
    "value": "var(--pl-type-font-brand)"
  },
  {
    "name": "--pl-display-md-size",
    "value": "var(--pl-type-size-900)"
  },
  {
    "name": "--pl-display-md-lineheight",
    "value": "var(--pl-type-lineheight-700)"
  },
  {
    "name": "--pl-display-md-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-heading-h1-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-heading-h1-size",
    "value": "var(--pl-type-size-800)"
  },
  {
    "name": "--pl-heading-h1-lineheight",
    "value": "var(--pl-type-lineheight-600)"
  },
  {
    "name": "--pl-heading-h1-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-heading-h2-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-heading-h2-size",
    "value": "var(--pl-type-size-700)"
  },
  {
    "name": "--pl-heading-h2-lineheight",
    "value": "var(--pl-type-lineheight-500)"
  },
  {
    "name": "--pl-heading-h2-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-heading-h3-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-heading-h3-size",
    "value": "var(--pl-type-size-600)"
  },
  {
    "name": "--pl-heading-h3-lineheight",
    "value": "var(--pl-type-lineheight-400)"
  },
  {
    "name": "--pl-heading-h3-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-heading-h4-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-heading-h4-size",
    "value": "var(--pl-type-size-500)"
  },
  {
    "name": "--pl-heading-h4-lineheight",
    "value": "var(--pl-type-lineheight-350)"
  },
  {
    "name": "--pl-heading-h4-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-body-lg-regular-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-lg-regular-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-body-lg-regular-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-body-lg-regular-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-body-md-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-md-medium-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-body-md-medium-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-body-md-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-title-md-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-md-semibold-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-title-md-semibold-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-title-md-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-title-sm-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-sm-semibold-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-title-sm-semibold-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-title-sm-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-label-lg-regular-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-lg-regular-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-label-lg-regular-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-label-lg-regular-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-caption-lg-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-caption-lg-size",
    "value": "var(--pl-type-size-200)"
  },
  {
    "name": "--pl-caption-lg-lineheight",
    "value": "var(--pl-type-lineheight-100)"
  },
  {
    "name": "--pl-caption-lg-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-caption-sm-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-caption-sm-size",
    "value": "var(--pl-type-size-100)"
  },
  {
    "name": "--pl-caption-sm-lineheight",
    "value": "var(--pl-type-lineheight-50)"
  },
  {
    "name": "--pl-caption-sm-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-title-lg-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-lg-semibold-size",
    "value": "var(--pl-type-size-500)"
  },
  {
    "name": "--pl-title-lg-semibold-lineheight",
    "value": "var(--pl-type-lineheight-350)"
  },
  {
    "name": "--pl-title-lg-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-title-lg-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-lg-medium-size",
    "value": "var(--pl-type-size-500)"
  },
  {
    "name": "--pl-title-lg-medium-lineheight",
    "value": "var(--pl-type-lineheight-350)"
  },
  {
    "name": "--pl-title-lg-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-title-md-bold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-md-bold-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-title-md-bold-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-title-md-bold-weight",
    "value": "var(--pl-type-weight-bold)"
  },
  {
    "name": "--pl-title-sm-bold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-sm-bold-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-title-sm-bold-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-title-sm-bold-weight",
    "value": "var(--pl-type-weight-bold)"
  },
  {
    "name": "--pl-title-lg-bold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-lg-bold-size",
    "value": "var(--pl-type-size-500)"
  },
  {
    "name": "--pl-title-lg-bold-lineheight",
    "value": "var(--pl-type-lineheight-350)"
  },
  {
    "name": "--pl-title-lg-bold-weight",
    "value": "var(--pl-type-weight-bold)"
  },
  {
    "name": "--pl-title-md-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-md-medium-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-title-md-medium-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-title-md-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-title-sm-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-title-sm-medium-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-title-sm-medium-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-title-sm-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-label-lg-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-lg-medium-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-label-lg-medium-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-label-lg-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-label-lg-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-lg-semibold-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-label-lg-semibold-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-label-lg-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-body-md-regular-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-md-regular-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-body-md-regular-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-body-md-regular-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-display-sm-font",
    "value": "var(--pl-type-font-brand)"
  },
  {
    "name": "--pl-display-sm-size",
    "value": "var(--pl-type-size-700)"
  },
  {
    "name": "--pl-display-sm-lineheight",
    "value": "var(--pl-type-lineheight-400)"
  },
  {
    "name": "--pl-display-sm-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-caption-lg-bold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-caption-lg-bold-size",
    "value": "var(--pl-type-size-200)"
  },
  {
    "name": "--pl-caption-lg-bold-lineheight",
    "value": "var(--pl-type-lineheight-100)"
  },
  {
    "name": "--pl-caption-lg-bold-weight",
    "value": "var(--pl-type-weight-bold)"
  },
  {
    "name": "--pl-body-lg-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-lg-semibold-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-body-lg-semibold-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-body-lg-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-body-md-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-md-semibold-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-body-md-semibold-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-body-md-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-caption-lg-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-caption-lg-medium-size",
    "value": "var(--pl-type-size-200)"
  },
  {
    "name": "--pl-caption-lg-medium-lineheight",
    "value": "var(--pl-type-lineheight-100)"
  },
  {
    "name": "--pl-caption-lg-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-body-lg-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-lg-medium-size",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-body-lg-medium-lineheight",
    "value": "var(--pl-type-lineheight-300)"
  },
  {
    "name": "--pl-body-lg-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-label-md-regular-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-md-regular-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-label-md-regular-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-label-md-regular-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-label-md-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-md-medium-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-label-md-medium-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-label-md-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-label-md-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-md-semibold-size",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-label-md-semibold-lineheight",
    "value": "var(--pl-type-lineheight-200)"
  },
  {
    "name": "--pl-label-md-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-body-sm-regular-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-sm-regular-size",
    "value": "var(--pl-type-size-250)"
  },
  {
    "name": "--pl-body-sm-regular-lineheight",
    "value": "var(--pl-type-lineheight-150)"
  },
  {
    "name": "--pl-body-sm-regular-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-body-sm-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-sm-medium-size",
    "value": "var(--pl-type-size-250)"
  },
  {
    "name": "--pl-body-sm-medium-lineheight",
    "value": "var(--pl-type-lineheight-150)"
  },
  {
    "name": "--pl-body-sm-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-body-sm-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-body-sm-semibold-size",
    "value": "var(--pl-type-size-250)"
  },
  {
    "name": "--pl-body-sm-semibold-lineheight",
    "value": "var(--pl-type-lineheight-150)"
  },
  {
    "name": "--pl-body-sm-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-label-sm-regular-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-sm-regular-size",
    "value": "var(--pl-type-size-250)"
  },
  {
    "name": "--pl-label-sm-regular-lineheight",
    "value": "var(--pl-type-lineheight-150)"
  },
  {
    "name": "--pl-label-sm-regular-weight",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-label-sm-medium-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-sm-medium-size",
    "value": "var(--pl-type-size-250)"
  },
  {
    "name": "--pl-label-sm-medium-lineheight",
    "value": "var(--pl-type-lineheight-150)"
  },
  {
    "name": "--pl-label-sm-medium-weight",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-label-sm-semibold-font",
    "value": "var(--pl-type-font-primary)"
  },
  {
    "name": "--pl-label-sm-semibold-size",
    "value": "var(--pl-type-size-250)"
  },
  {
    "name": "--pl-label-sm-semibold-lineheight",
    "value": "var(--pl-type-lineheight-150)"
  },
  {
    "name": "--pl-label-sm-semibold-weight",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-shadow-xs-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-xs-y",
    "value": "1px"
  },
  {
    "name": "--pl-shadow-xs-blur",
    "value": "2px"
  },
  {
    "name": "--pl-shadow-xs-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-xs-opacity",
    "value": "0.1"
  },
  {
    "name": "--pl-shadow-sm-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-sm-y",
    "value": "2px"
  },
  {
    "name": "--pl-shadow-sm-blur",
    "value": "8px"
  },
  {
    "name": "--pl-shadow-sm-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-sm-opacity",
    "value": "0.12"
  },
  {
    "name": "--pl-shadow-md-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-md-y",
    "value": "6px"
  },
  {
    "name": "--pl-shadow-md-blur",
    "value": "16px"
  },
  {
    "name": "--pl-shadow-md-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-md-opacity",
    "value": "0.14"
  },
  {
    "name": "--pl-shadow-lg-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-lg-y",
    "value": "10px"
  },
  {
    "name": "--pl-shadow-lg-blur",
    "value": "24px"
  },
  {
    "name": "--pl-shadow-lg-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-lg-opacity",
    "value": "0.16"
  },
  {
    "name": "--pl-shadow-xl-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-xl-y",
    "value": "20px"
  },
  {
    "name": "--pl-shadow-xl-blur",
    "value": "40px"
  },
  {
    "name": "--pl-shadow-xl-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-xl-opacity",
    "value": "0.18"
  },
  {
    "name": "--pl-shadow-overlay-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-overlay-y",
    "value": "12px"
  },
  {
    "name": "--pl-shadow-overlay-blur",
    "value": "32px"
  },
  {
    "name": "--pl-shadow-overlay-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-overlay-opacity",
    "value": "0.2"
  },
  {
    "name": "--pl-shadow-modal-x",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-modal-y",
    "value": "24px"
  },
  {
    "name": "--pl-shadow-modal-blur",
    "value": "60px"
  },
  {
    "name": "--pl-shadow-modal-spread",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-modal-opacity",
    "value": "0.25"
  },
  {
    "name": "--pl-shadow-elevation-primitives-0",
    "value": "0px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-2",
    "value": "2px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-4",
    "value": "4px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-6",
    "value": "6px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-8",
    "value": "8px"
  },
  {
    "name": "--pl-shadow-elevation-xs",
    "value": "var(--pl-shadow-elevation-primitives-1)"
  },
  {
    "name": "--pl-shadow-elevation-primitives-1",
    "value": "1px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-3",
    "value": "3px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-12",
    "value": "12px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-16",
    "value": "16px"
  },
  {
    "name": "--pl-shadow-elevation-primitives-24",
    "value": "24px"
  },
  {
    "name": "--pl-shadow-elevation-sm",
    "value": "var(--pl-shadow-elevation-primitives-2)"
  },
  {
    "name": "--pl-shadow-elevation-md",
    "value": "var(--pl-shadow-elevation-primitives-4)"
  },
  {
    "name": "--pl-shadow-elevation-lg",
    "value": "var(--pl-shadow-elevation-primitives-8)"
  },
  {
    "name": "--pl-shadow-elevation-xl",
    "value": "var(--pl-shadow-elevation-primitives-16)"
  },
  {
    "name": "--pl-shadow-elevation-xxl",
    "value": "var(--pl-shadow-elevation-primitives-24)"
  },
  {
    "name": "--pl-shadow-elevation-none",
    "value": "var(--pl-shadow-elevation-primitives-0)"
  },
  {
    "name": "--pl-radius-semantic-xs",
    "value": "var(--pl-radius-primitives-3)"
  },
  {
    "name": "--pl-radius-semantic-sm",
    "value": "var(--pl-radius-primitives-4)"
  },
  {
    "name": "--pl-radius-semantic-md",
    "value": "var(--pl-radius-primitives-5)"
  },
  {
    "name": "--pl-radius-semantic-lg",
    "value": "var(--pl-radius-primitives-6)"
  },
  {
    "name": "--pl-radius-semantic-xl",
    "value": "var(--pl-radius-primitives-7)"
  },
  {
    "name": "--pl-radius-semantic-xxl",
    "value": "var(--pl-radius-primitives-8)"
  },
  {
    "name": "--pl-radius-semantic-pill",
    "value": "var(--pl-radius-primitives-full)"
  },
  {
    "name": "--pl-radius-component-button-regular",
    "value": "var(--pl-radius-semantic-lg)"
  },
  {
    "name": "--pl-radius-component-button-pill",
    "value": "var(--pl-radius-semantic-pill)"
  },
  {
    "name": "--pl-radius-component-button-icon",
    "value": "var(--pl-radius-semantic-pill)"
  },
  {
    "name": "--pl-radius-component-card-icon",
    "value": "var(--pl-radius-semantic-pill)"
  },
  {
    "name": "--pl-radius-component-card-default",
    "value": "var(--pl-radius-semantic-lg)"
  },
  {
    "name": "--pl-radius-component-modal-sheet",
    "value": "var(--pl-radius-semantic-xxl)"
  },
  {
    "name": "--pl-radius-component-modal-dialog",
    "value": "var(--pl-radius-semantic-xxl)"
  },
  {
    "name": "--pl-radius-component-input-regular",
    "value": "var(--pl-radius-semantic-lg)"
  },
  {
    "name": "--pl-radius-component-input-compact",
    "value": "var(--pl-radius-semantic-md)"
  },
  {
    "name": "--pl-radius-primitives-0",
    "value": "0px"
  },
  {
    "name": "--pl-radius-primitives-8",
    "value": "24px"
  },
  {
    "name": "--pl-radius-primitives-full",
    "value": "999px"
  },
  {
    "name": "--pl-radius-primitives-5",
    "value": "12px"
  },
  {
    "name": "--pl-radius-primitives-6",
    "value": "16px"
  },
  {
    "name": "--pl-radius-primitives-4",
    "value": "8px"
  },
  {
    "name": "--pl-radius-primitives-1",
    "value": "2px"
  },
  {
    "name": "--pl-radius-primitives-3",
    "value": "6px"
  },
  {
    "name": "--pl-radius-primitives-7",
    "value": "20px"
  },
  {
    "name": "--pl-radius-primitives-2",
    "value": "4px"
  },
  {
    "name": "--pl-space-xxs",
    "value": "var(--pl-space-1)"
  },
  {
    "name": "--pl-space-xs",
    "value": "var(--pl-space-2)"
  },
  {
    "name": "--pl-space-sm",
    "value": "var(--pl-space-3)"
  },
  {
    "name": "--pl-space-md",
    "value": "var(--pl-space-4)"
  },
  {
    "name": "--pl-space-lg",
    "value": "var(--pl-space-5)"
  },
  {
    "name": "--pl-space-xl",
    "value": "var(--pl-space-6)"
  },
  {
    "name": "--pl-container-sm",
    "value": "var(--pl-space-4)"
  },
  {
    "name": "--pl-container-md",
    "value": "var(--pl-space-5)"
  },
  {
    "name": "--pl-container-xl",
    "value": "var(--pl-space-7)"
  },
  {
    "name": "--pl-container-lg",
    "value": "var(--pl-space-6)"
  },
  {
    "name": "--pl-chip-md-icon-gap",
    "value": "var(--pl-space-xxs)"
  },
  {
    "name": "--pl-button-md-padding-x",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-chip-md-padding-y",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-chip-sm-padding-y",
    "value": "var(--pl-space-xxs)"
  },
  {
    "name": "--pl-chip-md-padding-x",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-modal-sheet-section-gap",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-modal-dialog-padding",
    "value": "var(--pl-space-xl)"
  },
  {
    "name": "--pl-chip-sm-icon-gap",
    "value": "var(--pl-space-xxs)"
  },
  {
    "name": "--pl-chip-sm-padding-x",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-button-lg-padding-x",
    "value": "var(--pl-space-xl)"
  },
  {
    "name": "--pl-listitem-content-gap-sm",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-listitem-padding-y",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-button-sm-padding-y",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-modal-sheet-padding",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-input-label-gap",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-input-icon-gap",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-button-lg-padding-y",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-listitem-padding-x",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-modal-dialog-section-gap",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-button-sm-padding-x",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-input-padding-x",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-input-padding-y",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-listitem-content-gap-md",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-button-md-padding-y",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-card-gap",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-listitem-content-gap-lg",
    "value": "var(--pl-space-xl)"
  },
  {
    "name": "--pl-listitem-icon-gap",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-card-padding-sm",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-icon-sm-padding-x",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-icon-sm-padding-y",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-icon-md-padding-x",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-icon-md-padding-y",
    "value": "var(--pl-space-sm)"
  },
  {
    "name": "--pl-icon-lg-padding-x",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-icon-lg-padding-y",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-container-xs",
    "value": "var(--pl-space-3)"
  },
  {
    "name": "--pl-card-padding-md",
    "value": "var(--pl-space-md)"
  },
  {
    "name": "--pl-card-padding-xs",
    "value": "var(--pl-space-xs)"
  },
  {
    "name": "--pl-space-xxl",
    "value": "var(--pl-space-7)"
  },
  {
    "name": "--pl-space-xxxl",
    "value": "var(--pl-space-8)"
  },
  {
    "name": "--pl-container-xxl",
    "value": "var(--pl-space-8)"
  },
  {
    "name": "--pl-icon-sm",
    "value": "var(--pl-space-4)"
  },
  {
    "name": "--pl-icon-md",
    "value": "var(--pl-space-5)"
  },
  {
    "name": "--pl-icon-lg",
    "value": "var(--pl-space-6)"
  },
  {
    "name": "--pl-icon-xs",
    "value": "var(--pl-space-3)"
  },
  {
    "name": "--pl-size-primitives-1",
    "value": "24px"
  },
  {
    "name": "--pl-size-primitives-2",
    "value": "32px"
  },
  {
    "name": "--pl-size-primitives-3",
    "value": "36px"
  },
  {
    "name": "--pl-size-primitives-4",
    "value": "40px"
  },
  {
    "name": "--pl-size-primitives-5",
    "value": "44px"
  },
  {
    "name": "--pl-size-primitives-6",
    "value": "48px"
  },
  {
    "name": "--pl-size-primitives-7",
    "value": "56px"
  },
  {
    "name": "--pl-size-primitives-8",
    "value": "64px"
  },
  {
    "name": "--pl-size-primitives-9",
    "value": "72px"
  },
  {
    "name": "--pl-size-primitives-10",
    "value": "80px"
  },
  {
    "name": "--pl-size-primitives-11",
    "value": "96px"
  },
  {
    "name": "--pl-size-primitives-12",
    "value": "140px"
  },
  {
    "name": "--pl-size-componentsize-24",
    "value": "var(--pl-size-primitives-1)"
  },
  {
    "name": "--pl-size-componentsize-32",
    "value": "var(--pl-size-primitives-2)"
  },
  {
    "name": "--pl-size-componentsize-36",
    "value": "var(--pl-size-primitives-3)"
  },
  {
    "name": "--pl-size-componentsize-40",
    "value": "var(--pl-size-primitives-4)"
  },
  {
    "name": "--pl-size-componentsize-48",
    "value": "var(--pl-size-primitives-6)"
  },
  {
    "name": "--pl-size-componentsize-64",
    "value": "var(--pl-size-primitives-8)"
  },
  {
    "name": "--pl-size-componentsize-96",
    "value": "var(--pl-size-primitives-11)"
  },
  {
    "name": "--pl-size-componentsize-140",
    "value": "var(--pl-size-primitives-12)"
  },
  {
    "name": "--pl-size-componentsize-56",
    "value": "var(--pl-size-primitives-7)"
  },
  {
    "name": "--pl-size-componentsize-72",
    "value": "var(--pl-size-primitives-9)"
  },
  {
    "name": "--pl-size-componentsize-80",
    "value": "var(--pl-size-primitives-10)"
  },
  {
    "name": "--pl-symbol-size-sm",
    "value": "var(--pl-type-size-300)"
  },
  {
    "name": "--pl-symbol-size-md",
    "value": "var(--pl-type-size-400)"
  },
  {
    "name": "--pl-symbol-size-lg",
    "value": "var(--pl-type-size-500)"
  },
  {
    "name": "--pl-symbol-size-xl",
    "value": "var(--pl-type-size-600)"
  },
  {
    "name": "--pl-symbol-weight-regular",
    "value": "var(--pl-type-weight-regular)"
  },
  {
    "name": "--pl-symbol-weight-medium",
    "value": "var(--pl-type-weight-medium)"
  },
  {
    "name": "--pl-symbol-weight-semibold",
    "value": "var(--pl-type-weight-semibold)"
  },
  {
    "name": "--pl-symbol-weight-bold",
    "value": "var(--pl-type-weight-bold)"
  },
  {
    "name": "--pl-symbol-size-xs",
    "value": "var(--pl-type-size-100)"
  },
  {
    "name": "--pl-symbol-size-xxl",
    "value": "var(--pl-type-size-700)"
  },
  {
    "name": "--pl-border-primitives-1",
    "value": "1px"
  },
  {
    "name": "--pl-border-primitives-2",
    "value": "2px"
  },
  {
    "name": "--pl-border-semantic-100",
    "value": "var(--pl-border-primitives-1)"
  },
  {
    "name": "--pl-border-semantic-200",
    "value": "var(--pl-border-primitives-2)"
  },
  {
    "name": "--pl-shadow-rgb",
    "value": "2 2 3"
  },
  {
    "name": "--pl-elevation-xs",
    "value": "var(--pl-shadow-xs-x) var(--pl-shadow-xs-y) var(--pl-shadow-xs-blur) var(--pl-shadow-xs-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-xs-opacity))"
  },
  {
    "name": "--pl-elevation-sm",
    "value": "var(--pl-shadow-sm-x) var(--pl-shadow-sm-y) var(--pl-shadow-sm-blur) var(--pl-shadow-sm-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-sm-opacity))"
  },
  {
    "name": "--pl-elevation-md",
    "value": "var(--pl-shadow-md-x) var(--pl-shadow-md-y) var(--pl-shadow-md-blur) var(--pl-shadow-md-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-md-opacity))"
  },
  {
    "name": "--pl-elevation-lg",
    "value": "var(--pl-shadow-lg-x) var(--pl-shadow-lg-y) var(--pl-shadow-lg-blur) var(--pl-shadow-lg-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-lg-opacity))"
  },
  {
    "name": "--pl-elevation-xl",
    "value": "var(--pl-shadow-xl-x) var(--pl-shadow-xl-y) var(--pl-shadow-xl-blur) var(--pl-shadow-xl-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-xl-opacity))"
  },
  {
    "name": "--pl-elevation-overlay",
    "value": "var(--pl-shadow-overlay-x) var(--pl-shadow-overlay-y) var(--pl-shadow-overlay-blur) var(--pl-shadow-overlay-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-overlay-opacity))"
  },
  {
    "name": "--pl-elevation-modal",
    "value": "var(--pl-shadow-modal-x) var(--pl-shadow-modal-y) var(--pl-shadow-modal-blur) var(--pl-shadow-modal-spread) rgb(var(--pl-shadow-rgb) / var(--pl-shadow-modal-opacity))"
  }
];
window.PL_THEMED = [
  "--pl-text-primary",
  "--pl-text-secondary",
  "--pl-text-disabled",
  "--pl-text-inverse",
  "--pl-text-link",
  "--pl-text-status-success",
  "--pl-text-status-warning",
  "--pl-text-status-danger",
  "--pl-text-status-neutral",
  "--pl-text-status-red",
  "--pl-text-status-purple",
  "--pl-text-status-green",
  "--pl-text-status-yellow",
  "--pl-text-status-orange",
  "--pl-text-status-blue",
  "--pl-bg-default",
  "--pl-bg-subtle",
  "--pl-bg-inverse",
  "--pl-surface-default",
  "--pl-surface-inset",
  "--pl-surface-static-black",
  "--pl-surface-disabled",
  "--pl-surface-status-successsubtle",
  "--pl-surface-status-warningsubtle",
  "--pl-surface-status-dangersubtle",
  "--pl-surface-variant-neutral",
  "--pl-surface-variant-red",
  "--pl-surface-variant-purple",
  "--pl-surface-variant-green",
  "--pl-surface-variant-yellow",
  "--pl-surface-variant-orange",
  "--pl-surface-variant-blue",
  "--pl-border-default",
  "--pl-border-disabled",
  "--pl-border-danger",
  "--pl-accent-default",
  "--pl-accent-hover",
  "--pl-accent-pressed",
  "--pl-border-focus",
  "--pl-surface-subtle",
  "--pl-surface-hover",
  "--pl-surface-pressed",
  "--pl-surface-selected",
  "--pl-text-emphasis",
  "--pl-accent-subtle",
  "--pl-accent-subtlehover",
  "--pl-accent-subtlepressed",
  "--pl-accent-focusring",
  "--pl-border-subtle",
  "--pl-icon-default",
  "--pl-icon-subtle",
  "--pl-icon-disabled",
  "--pl-icon-inverse",
  "--pl-icon-green",
  "--pl-icon-red",
  "--pl-icon-orange",
  "--pl-icon-yellow",
  "--pl-icon-purple",
  "--pl-icon-blue",
  "--pl-icon-rating",
  "--pl-text-onaccent",
  "--pl-text-price-discount",
  "--pl-icon-success",
  "--pl-surface-static-white",
  "--pl-button-secondary-bg-default",
  "--pl-button-secondary-bg-hovered",
  "--pl-button-secondary-bg-pressed",
  "--pl-button-secondary-bg-disabled",
  "--pl-button-neutral-bg-default",
  "--pl-button-neutral-bg-hovered",
  "--pl-button-neutral-bg-pressed",
  "--pl-button-neutral-bg-disabled",
  "--pl-button-neutralsolid-bg-default",
  "--pl-button-neutralsolid-bg-hovered",
  "--pl-button-neutralsolid-bg-pressed",
  "--pl-button-neutralsolid-bg-disabled",
  "--pl-button-outline-bg-default",
  "--pl-button-outline-bg-hovered",
  "--pl-button-outline-bg-pressed",
  "--pl-button-outline-bg-disabled",
  "--pl-button-destructive-bg-default",
  "--pl-button-destructive-bg-hovered",
  "--pl-button-destructive-bg-pressed",
  "--pl-button-destructive-bg-disabled",
  "--pl-button-destructive-fg-disabled",
  "--pl-button-destructive-fg-default",
  "--pl-button-secondary-fg-default",
  "--pl-button-secondary-fg-disabled",
  "--pl-button-neutral-fg-default",
  "--pl-button-neutral-fg-disabled",
  "--pl-button-neutralsolid-fg-default",
  "--pl-button-neutralsolid-fg-disabled",
  "--pl-button-outline-fg-default",
  "--pl-button-outline-fg-disabled",
  "--pl-button-inverse-bg-default",
  "--pl-button-inverse-bg-hovered",
  "--pl-button-inverse-bg-pressed",
  "--pl-button-inverse-bg-disabled",
  "--pl-button-inverse-fg-default",
  "--pl-button-inverse-fg-disabled",
  "--pl-button-ghost-bg-default",
  "--pl-button-ghost-bg-hovered",
  "--pl-button-ghost-bg-pressed",
  "--pl-button-ghost-bg-disabled",
  "--pl-button-ghost-fg-default",
  "--pl-button-ghost-fg-disabled",
  "--pl-shadow-default",
  "--pl-text-static-black",
  "--pl-border-white"
];
