// Generated by build-typography.mjs — do not edit by hand.
window.PL_ROLE_STYLES = [
  {
    "figma": "role/pageTitle",
    "cls": "pl-page-title",
    "token": "display-md"
  },
  {
    "figma": "role/contentTitle",
    "cls": "pl-content-title",
    "token": "display-sm"
  },
  {
    "figma": "role/sectionHeader",
    "cls": "pl-section-header",
    "token": "heading-h3"
  },
  {
    "figma": "role/cardTitle",
    "cls": "pl-card-title",
    "token": "title-lg-medium"
  },
  {
    "figma": "role/listTitle",
    "cls": "pl-list-title",
    "token": "title-md-medium"
  },
  {
    "figma": "role/tabLabel",
    "cls": "pl-tab-label",
    "token": "caption-lg"
  },
  {
    "figma": "role/captionPrimary",
    "cls": "pl-caption-primary",
    "token": "caption-lg"
  },
  {
    "figma": "role/captionPrimary medium",
    "cls": "pl-caption-primary-medium",
    "token": "caption-lg-medium"
  },
  {
    "figma": "role/captionPrimary bold",
    "cls": "pl-caption-primary-bold",
    "token": "caption-lg-bold"
  },
  {
    "figma": "role/captionSecondary",
    "cls": "pl-caption-secondary",
    "token": "caption-sm"
  },
  {
    "figma": "role/body/large/bodyLarge regular",
    "cls": "pl-body-large-regular",
    "token": "body-lg-regular"
  },
  {
    "figma": "role/body/large/bodyLarge medium",
    "cls": "pl-body-large-medium",
    "token": "body-lg-medium"
  },
  {
    "figma": "role/body/large/bodyLarge semiBold",
    "cls": "pl-body-large-semibold",
    "token": "body-lg-semibold"
  },
  {
    "figma": "role/body/medium/bodyMedium regular",
    "cls": "pl-body-medium-regular",
    "token": "body-md-regular"
  },
  {
    "figma": "role/body/medium/bodyMedium medium",
    "cls": "pl-body-medium-medium",
    "token": "body-md-medium"
  },
  {
    "figma": "role/body/medium/bodyMedium semiBold",
    "cls": "pl-body-medium-semibold",
    "token": "body-md-semibold"
  },
  {
    "figma": "role/body/small/bodySmall regular",
    "cls": "pl-body-small-regular",
    "token": "body-sm-regular"
  },
  {
    "figma": "role/body/small/bodySmall medium",
    "cls": "pl-body-small-medium",
    "token": "body-sm-medium"
  },
  {
    "figma": "role/body/small/bodySmall semiBold",
    "cls": "pl-body-small-semibold",
    "token": "body-sm-semibold"
  },
  {
    "figma": "role/button label/large/buttonLabelLarge medium",
    "cls": "pl-button-label-large-medium",
    "token": "label-lg-medium"
  },
  {
    "figma": "role/button label/large/buttonLabelLarge semibold",
    "cls": "pl-button-label-large-semibold",
    "token": "label-lg-semibold"
  },
  {
    "figma": "role/button label/medium/buttonLabelMedium medium",
    "cls": "pl-button-label-medium-medium",
    "token": "label-md-medium"
  },
  {
    "figma": "role/button label/medium/buttonLabelMedium semibold",
    "cls": "pl-button-label-medium-semibold",
    "token": "label-md-semibold"
  },
  {
    "figma": "role/button label/small/buttonLabelSmall medium",
    "cls": "pl-button-label-small-medium",
    "token": "label-sm-medium"
  },
  {
    "figma": "role/button label/small/buttonLabelSmall semibold",
    "cls": "pl-button-label-small-semibold",
    "token": "label-sm-semibold"
  },
  {
    "figma": "role/input label/large/inputLabelLarge medium",
    "cls": "pl-input-label-large-medium",
    "token": "label-lg-medium"
  },
  {
    "figma": "role/input label/large/inputLabelLarge semiBold",
    "cls": "pl-input-label-large-semibold",
    "token": "label-lg-semibold"
  },
  {
    "figma": "role/input label/medium/inputLabelMedium medium",
    "cls": "pl-input-label-medium-medium",
    "token": "label-md-medium"
  },
  {
    "figma": "role/input label/medium/inputLabelMedium semiBold",
    "cls": "pl-input-label-medium-semibold",
    "token": "label-md-semibold"
  }
];
